POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "displayName": "ashley",
    "username": "ashley",
    "email": "ashley@gmail.com",
    "password": "123456789"
}

###

POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "ashley@gmail.com",
    "password": "123456789"
}

###

PUT http://localhost:5000/lists/edit/6288f21e789365d901b4c7ee
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Mjg4OTY5YTM0M2YxZTk2MGM5ZmYzMzciLCJkaXNwbGF5TmFtZSI6ImJvYiIsInVzZXJuYW1lIjoiYm9iIiwiZW1haWwiOiJib2JAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAka2NMeUpJZUlBeGs0bGNjTGt3dnV2dXdjSktQNkk3cVh6THl5TjE4R3F3S2dORnpETmdkamEiLCJib29rbWFya2VkVHdlZXRzIjpbXSwibGlrZWRUd2VldHMiOltdLCJmb2xsb3dlcnMiOltdLCJmb2xsb3dpbmciOltdLCJkYXRlIjoiMjAyMi0wNS0yMVQwNzozNDoxMC41NTZaIiwiaWF0IjoxNjUzMTg4NDY0LCJleHAiOjE2NTMxODkwNjR9.x_xhuYK7q2ooPDbnjXimpiY7xiX_RntZP0_JgYdknDo

{   
    "description": "This description has been added by editing the list!!"
}

###

POST http://localhost:5000/auth/refresh/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Mjg4OTY5YTM0M2YxZTk2MGM5ZmYzMzciLCJkaXNwbGF5TmFtZSI6ImJvYiIsInVzZXJuYW1lIjoiYm9iIiwiZW1haWwiOiJib2JAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAka2NMeUpJZUlBeGs0bGNjTGt3dnV2dXdjSktQNkk3cVh6THl5TjE4R3F3S2dORnpETmdkamEiLCJib29rbWFya2VkVHdlZXRzIjpbXSwibGlrZWRUd2VldHMiOltdLCJmb2xsb3dlcnMiOltdLCJmb2xsb3dpbmciOltdLCJkYXRlIjoiMjAyMi0wNS0yMVQwNzozNDoxMC41NTZaIiwiX192IjowLCJpYXQiOjE2NTMxMTg2MzR9.70iBhRp-XbvjC6pRYAjCRp_yhFs54QOI1nmXBR0lDUk"
}
