POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "displayName": "bob",
    "username": "bob",
    "email": "bob@gmail.com",
    "password": "123456789"
}

###

POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "bob@gmail.com",
    "password": "123456789"
}

###

PUT http://localhost:5000/posts/like/62866cf4c04b850ee8e6cc38
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Mjg2NmM5YWMwNGI4NTBlZThlNmNjMzMiLCJ1c2VybmFtZSI6ImJvYiIsImVtYWlsIjoiYm9iQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJFBBWnk3QVpsTHdvR0dCLzhPNEZHSk9mYjlUWTVEbko1OEhmVmpBREtwbVJYbVB3aHhlS2d1IiwiaWF0IjoxNjUyOTc3NDE0LCJleHAiOjE2NTI5NzgwMTR9.zTN95nXaiZqcj4MQha7t3Wb1kUX14Tnd8j8lQt2umIA

###

POST http://localhost:5000/auth/refresh/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Mjg2NmM5YWMwNGI4NTBlZThlNmNjMzMiLCJkaXNwbGF5TmFtZSI6ImJvYiIsInVzZXJuYW1lIjoiYm9iIiwiZW1haWwiOiJib2JAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkUEFaeTdBWmxMd29HR0IvOE80RkdKT2ZiOVRZNURuSjU4SGZWakFES3BtUlhtUHdoeGVLZ3UiLCJsaWtlZFBvc3RzIjpbXSwiZGF0ZSI6IjIwMjItMDUtMTlUMTY6MTI6MzMuODc0WiIsIl9fdiI6MCwiaWF0IjoxNjUyOTc2Nzk3fQ.cm1lJKjPdDEN3-o6TGO41AeXUeC8jUDsyuHJf_XJCmY"
}
